/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** AgentKern SDK version */
export const VERSION: string
/** Agent configuration options. */
export interface AgentConfig {
  /** Agent name/label */
  name: string
  /** Default proof expiry in seconds */
  proofExpirySeconds?: number
  /** Issuer identifier (DID or domain) */
  issuer?: string
}
/** Liability Proof - A signed JWT proving authorization. */
export interface LiabilityProof {
  /** JWT algorithm */
  alg: string
  /** JWT type */
  typ: string
  /** Key ID (public key) */
  kid: string
  /** Issuer (DID) */
  issuer: string
  /** Subject (agent DID) */
  subject: string
  /** Authorized action */
  action: string
  /** Issued at (Unix timestamp) */
  issuedAt: number
  /** Expiration (Unix timestamp) */
  expiresAt: number
  /** JWT ID */
  jti: string
  /** Full raw JWT string */
  jwt: string
}
/** Parse a JWT string into a LiabilityProof. */
export declare function parseProof(jwt: string): LiabilityProof
/** Check if a proof is expired. */
export declare function isProofExpired(proof: LiabilityProof): boolean
/** A2A Message types. */
export const enum MessageType {
  Request = 'Request',
  Response = 'Response',
  Notification = 'Notification',
  Error = 'Error',
  Ping = 'Ping',
  Pong = 'Pong',
  Capabilities = 'Capabilities'
}
/** Create an A2A request message. */
export declare function createA2ARequest(from: string, to: string, payload: any): string
/** Create an A2A notification message. */
export declare function createA2ANotification(from: string, to: string, payload: any): string
/** Parse an A2A message from JSON. */
export declare function parseA2AMessage(json: string): any
/** Agent - The core identity unit in AgentKern. */
export declare class Agent {
  /** Generate a new Agent with a random Ed25519 keypair. */
  static generate(name: string): Agent
  /** Generate a new Agent with custom configuration. */
  static generateWithConfig(config: AgentConfig): Agent
  /** Restore an Agent from an existing keypair seed (base64url encoded). */
  static fromSeed(name: string, seedBase64: string): Agent
  /** Get the agent's unique ID (DID format). */
  get id(): string
  /** Get the agent's name. */
  get name(): string
  /** Get the agent's public key (base64url encoded). */
  get publicKey(): string
  /**
   * Get the keypair seed for persistence (base64url encoded).
   * WARNING: This is sensitive key material. Store securely.
   */
  get seed(): string
  /** Sign arbitrary data (returns base64url signature). */
  sign(data: Buffer): string
  /** Sign a string message (returns base64url signature). */
  signMessage(message: string): string
  /** Create a Liability Proof for an action. */
  createProof(action: string): LiabilityProof
  /** Create a Liability Proof with custom expiry (seconds). */
  createProofWithExpiry(action: string, expirySeconds: number): LiabilityProof
  /** Verify a Liability Proof (static method). */
  static verifyProof(proof: LiabilityProof): boolean
}
