/* auto-generated by NAPI-RS */
/* eslint-disable */
/** TEE Attestation result. */
export interface AttestationResult {
  platform: string
  quote: string
  measurement: string
  nonce: string
  timestamp: number
}

/** Carbon budget configuration. */
export interface CarbonBudgetConfig {
  dailyLimitGrams: number
  monthlyLimitGrams?: number
  blockOnExceed: boolean
}

/** Check carbon budget for an agent. */
export declare function checkCarbonBudget(agentId: string, estimatedGrams: number): boolean

/** Get TEE attestation proof. */
export declare function getAttestation(nonce: string): Promise<AttestationResult>

/** Initialize the AgentKern native runtime. */
export declare function initRuntime(): string

/** Verify an agent action using Rust Gate engine. */
export declare function verifyAction(request: VerifyRequest): Promise<VerifyResult>

/** Verification request from Gateway. */
export interface VerifyRequest {
  agentId: string
  action: string
  context: string
}

/** Verification result to Gateway. */
export interface VerifyResult {
  allowed: boolean
  evaluatedPolicies: Array<string>
  blockingPolicies: Array<string>
  riskScore: number
  reasoning?: string
  latencyMs: number
}
