#!/bin/bash
# =============================================================================
# AgentKern Chaos Drill Script
# =============================================================================
# Enables chaos engineering in staging to validate system resilience.
#
# Usage:
#   ./scripts/chaos_drill.sh start [profile]
#   ./scripts/chaos_drill.sh stop
#   ./scripts/chaos_drill.sh status
#
# Profiles:
#   light    - 5% failure rate, 50ms delay (baseline)
#   moderate - 15% failure rate, 200ms delay (standard chaos)
#   heavy    - 30% failure rate, 500ms delay (stress test)
#   custom   - Uses CHAOS_* env vars directly
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Profile configurations
set_profile() {
    case "${1:-moderate}" in
        light)
            export CHAOS_FAILURE_RATE="0.05"
            export CHAOS_DELAY_MS="50"
            log_info "Using LIGHT chaos profile: 5% failure, 50ms delay"
            ;;
        moderate)
            export CHAOS_FAILURE_RATE="0.15"
            export CHAOS_DELAY_MS="200"
            log_info "Using MODERATE chaos profile: 15% failure, 200ms delay"
            ;;
        heavy)
            export CHAOS_FAILURE_RATE="0.30"
            export CHAOS_DELAY_MS="500"
            log_info "Using HEAVY chaos profile: 30% failure, 500ms delay"
            ;;
        custom)
            log_info "Using CUSTOM chaos profile from environment"
            log_info "  CHAOS_FAILURE_RATE: ${CHAOS_FAILURE_RATE:-0.0}"
            log_info "  CHAOS_DELAY_MS: ${CHAOS_DELAY_MS:-0}"
            ;;
        *)
            log_error "Unknown profile: $1"
            log_info "Available: light, moderate, heavy, custom"
            exit 1
            ;;
    esac
}

# Start chaos drill
start_chaos() {
    local profile="${1:-moderate}"
    
    log_info "Starting Chaos Drill..."
    log_warn "This will introduce artificial failures and latency!"
    
    # Set profile variables
    set_profile "$profile"
    
    # Enable chaos
    export CHAOS_ENABLED="true"
    
    # Export to .env.chaos for other processes
    cat > "${PROJECT_ROOT}/.env.chaos" <<EOF
# Chaos Drill Configuration - Generated by chaos_drill.sh
# Profile: $profile
# Started: $(date -Iseconds)
CHAOS_ENABLED=true
CHAOS_FAILURE_RATE=${CHAOS_FAILURE_RATE}
CHAOS_DELAY_MS=${CHAOS_DELAY_MS}
EOF
    
    log_info "Chaos configuration written to .env.chaos"
    log_info ""
    log_info "To apply chaos to running server:"
    log_info "  source .env.chaos && cargo run -p agentkern-server"
    log_info ""
    log_info "Or set in Docker/K8s:"
    log_info "  - CHAOS_ENABLED=true"
    log_info "  - CHAOS_FAILURE_RATE=${CHAOS_FAILURE_RATE}"
    log_info "  - CHAOS_DELAY_MS=${CHAOS_DELAY_MS}"
    
    # Run validation tests if requested
    if [[ "${RUN_TESTS:-false}" == "true" ]]; then
        log_info ""
        log_info "Running chaos validation tests..."
        run_validation_tests
    fi
}

# Stop chaos drill
stop_chaos() {
    log_info "Stopping Chaos Drill..."
    
    # Write disabled config
    cat > "${PROJECT_ROOT}/.env.chaos" <<EOF
# Chaos Drill Configuration - DISABLED
# Stopped: $(date -Iseconds)
CHAOS_ENABLED=false
CHAOS_FAILURE_RATE=0.0
CHAOS_DELAY_MS=0
EOF
    
    log_info "Chaos disabled in .env.chaos"
    log_info "Restart your server to apply changes"
}

# Show current status
show_status() {
    if [[ -f "${PROJECT_ROOT}/.env.chaos" ]]; then
        log_info "Current chaos configuration:"
        cat "${PROJECT_ROOT}/.env.chaos"
    else
        log_info "No chaos configuration file found"
        log_info "Chaos is disabled by default"
    fi
}

# Run validation tests during chaos
run_validation_tests() {
    log_info "Running validation tests under chaos conditions..."
    
    # These tests verify the system remains functional even with chaos
    local test_results=()
    local all_passed=true
    
    # Test 1: Health check should still respond
    log_info "Test 1: Health endpoint availability..."
    if curl -sf "http://localhost:8080/health" > /dev/null 2>&1; then
        test_results+=("✓ Health endpoint: PASS")
    else
        test_results+=("✗ Health endpoint: FAIL")
        all_passed=false
    fi
    
    # Test 2: Some requests should succeed (chaos is probabilistic)
    log_info "Test 2: Probabilistic request success..."
    local success_count=0
    for i in {1..10}; do
        if curl -sf "http://localhost:8080/api/v1/arbiter/health" > /dev/null 2>&1; then
            ((success_count++))
        fi
    done
    if [[ $success_count -gt 0 ]]; then
        test_results+=("✓ Request success rate: $success_count/10")
    else
        test_results+=("✗ Request success rate: 0/10 (all failed)")
        all_passed=false
    fi
    
    # Test 3: Database connectivity should be maintained
    log_info "Test 3: Database connectivity..."
    if curl -sf "http://localhost:8080/api/v1/identity/health" > /dev/null 2>&1; then
        test_results+=("✓ Database connectivity: PASS")
    else
        test_results+=("✗ Database connectivity: UNCERTAIN")
    fi
    
    # Print results
    log_info ""
    log_info "=== Chaos Validation Results ==="
    for result in "${test_results[@]}"; do
        echo "  $result"
    done
    
    if $all_passed; then
        log_info ""
        log_info "System remains functional under chaos conditions!"
    else
        log_warn ""
        log_warn "Some tests failed - review system behavior"
    fi
}

# Print usage
usage() {
    echo "Usage: $0 {start|stop|status} [profile]"
    echo ""
    echo "Commands:"
    echo "  start [profile]  - Enable chaos with specified profile"
    echo "  stop             - Disable chaos"
    echo "  status           - Show current chaos configuration"
    echo ""
    echo "Profiles:"
    echo "  light    - 5% failure, 50ms delay"
    echo "  moderate - 15% failure, 200ms delay (default)"
    echo "  heavy    - 30% failure, 500ms delay"
    echo "  custom   - Use CHAOS_* environment variables"
    echo ""
    echo "Options:"
    echo "  RUN_TESTS=true  - Run validation tests after starting"
    echo ""
    echo "Examples:"
    echo "  $0 start light"
    echo "  $0 start heavy"
    echo "  RUN_TESTS=true $0 start moderate"
    echo "  $0 stop"
}

# Main
case "${1:-}" in
    start)
        start_chaos "${2:-moderate}"
        ;;
    stop)
        stop_chaos
        ;;
    status)
        show_status
        ;;
    *)
        usage
        exit 1
        ;;
esac
