/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function attest(nonce: string): string
/** Prompt Injection Guard (Hot Path: 0ms) */
export declare function guardPrompt(prompt: string): string
/** RAG Context Guard (Hot Path: 0ms) */
export declare function guardContext(chunks: Array<string>): string
/**
 * Gate Engine Verification (Hot Path: 0ms)
 * Executes full policy verification using the embedded engine.
 */
export declare function verify(agentId: string, action: string, contextJson?: string | undefined | null): Promise<string>
